package tofu

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestVarsFromTFVars(t *testing.T) {
	src := []byte(`
name = "pihole"
phrase = "two words"
quoted = "\"quoted\""
symbol = "a$b#c"
replicas = 3
enabled = true
tags = ["a", "b"]
creds = { user = "u", pass = "p" }
missing = null
`)

	env, err := varsFromTFVars(src, "default.tfvars")
	if err != nil {
		t.Fatal(err)
	}

	// OpenTofu takes TF_VAR_ contents literally for string variables and parses them
	// as HCL only for complex types, so a string must arrive unquoted and a list or
	// map as JSON. A null entry assigns nothing and is skipped.
	want := map[string]string{
		"TF_VAR_name":     "pihole",
		"TF_VAR_phrase":   "two words",
		"TF_VAR_quoted":   `"quoted"`,
		"TF_VAR_symbol":   "a$b#c",
		"TF_VAR_replicas": "3",
		"TF_VAR_enabled":  "true",
		"TF_VAR_tags":     `["a","b"]`,
		"TF_VAR_creds":    `{"pass":"p","user":"u"}`,
	}

	got := map[string]string{}

	for _, entry := range env {
		name, value, ok := strings.Cut(entry, "=")
		if !ok {
			t.Fatalf("malformed assignment %q", entry)
		}

		got[name] = value
	}

	if len(got) != len(want) {
		t.Fatalf("got %d variables, want %d: %v", len(got), len(want), got)
	}

	for name, value := range want {
		// OpenTofu parses TF_VAR_ contents as HCL, so the literal has to survive.
		if got[name] != value {
			t.Errorf("%s = %s, want %s", name, got[name], value)
		}
	}
}

func TestVarsFromTFVarsRejectsExpressionsWithoutLeaking(t *testing.T) {
	src := []byte(`
user = "kept"
password = file("/tmp/value-that-must-not-be-logged")
`)

	_, err := varsFromTFVars(src, "default.tfvars")
	if err == nil {
		t.Fatal("expected a non-literal variable to be rejected")
	}

	if strings.Contains(err.Error(), "must-not-be-logged") {
		t.Errorf("the error message leaked the value: %v", err)
	}

	if !strings.Contains(err.Error(), "password") {
		t.Errorf("the error message should name the variable: %v", err)
	}
}

func TestVarsFromTFVarsRejectsBrokenText(t *testing.T) {
	if _, err := varsFromTFVars([]byte("password = "), "default.tfvars"); err == nil {
		t.Error("expected unparsable tfvars to be rejected")
	}
}

func TestFingerprintAndNeedsInit(t *testing.T) {
	t.Chdir(t.TempDir())

	write := func(name, body string) {
		t.Helper()

		if err := os.MkdirAll(filepath.Dir(name), 0o755); err != nil {
			t.Fatal(err)
		}

		if err := os.WriteFile(name, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	write("config.tf", "terraform {\n  required_providers {\n    kubectl = { source = \"alekc/kubectl\" }\n  }\n}\n")
	write("main.tf", "locals {\n  a = 1\n}\n")
	write(".terraform.lock.hcl", "provider \"registry.opentofu.org/alekc/kubectl\" {}\n")
	write(".terraform/modules/vendored/main.tf", "resource \"x\" \"y\" { source = \"changed-inside-terraform-does-not-count\" }\n")

	first, err := fingerprint()
	if err != nil {
		t.Fatal(err)
	}

	if !needsInit() {
		t.Error("a directory with no stored fingerprint should need init")
	}

	if err := os.WriteFile(fingerprintPath, []byte(first+"\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	if needsInit() {
		t.Error("stored fingerprint should mean no init")
	}

	// A source declaration changes what init resolves.
	write("main.tf", "module \"nfs\" {\n  source = \"../modules/nfs\"\n}\n")

	second, err := fingerprint()
	if err != nil {
		t.Fatal(err)
	}

	if second == first {
		t.Error("a new source declaration must change the fingerprint")
	}

	if !needsInit() {
		t.Error("a stale fingerprint should mean init")
	}

	// A comment does not.
	write("main.tf", "module \"nfs\" {\n  source = \"../modules/nfs\"\n}\n\n# a note\n")

	third, err := fingerprint()
	if err != nil {
		t.Fatal(err)
	}

	if third != second {
		t.Error("an unrelated comment must not change the fingerprint")
	}

	// Files under .terraform are generated by init and must be ignored.
	write(".terraform/modules/vendored/main.tf", "resource \"x\" \"y\" { source = \"changed again\" }\n")

	fourth, err := fingerprint()
	if err != nil {
		t.Fatal(err)
	}

	if fourth != third {
		t.Error("the fingerprint must not read inside .terraform")
	}
}

func TestIsConfigDir(t *testing.T) {
	empty := t.TempDir()
	if isConfigDir(empty) {
		t.Error("an empty directory is not configuration")
	}

	if err := os.WriteFile(filepath.Join(empty, "main.tf"), []byte("locals {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	if !isConfigDir(empty) {
		t.Error("a directory with a .tf file is configuration")
	}

	secrets := t.TempDir()
	if err := os.MkdirAll(filepath.Join(secrets, "secrets"), 0o755); err != nil {
		t.Fatal(err)
	}

	if !isConfigDir(secrets) {
		t.Error("a directory with a secrets directory is configuration")
	}
}
